---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

inputs:
- name: attendee-service-source

params:
  USER:
  PASSWORD:

run:
  path: attendee-service-source/ci/tasks/remove-blue.sh
