---
resources:
- name: attendee-service-source
  type: git
  source:
    uri: https://github.com/amymb/pcf-attendee-service-code  #<---- REPLACE ME
    branch: master

- name: deploy-attendee-service
  type: cf
  source:
    api: api.run.pivotal.io        #<---- REPLACE ME
    username: {{cf-user}}
    password: {{cf-password}}
    organization: Pivotal-Enablement    #<---- REPLACE ME
    space: staging         #<---- REPLACE ME
    skip_cert_check: true

jobs:
- name: test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
  - task: test
    file: attendee-service-source/ci/tasks/test.yml

- name: deploy_green
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service-source/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service-source/manifest.yml
      path: package-output/attendee-service.jar 

- name: smoke_test_1
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [deploy_green]
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: https://attendee-service-automatic-vitrifiability-test.cfapps.io   #<---- REPLACE ME

- name: reroute_green
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [smoke_test_1]
  - task: reroute_green
    file: attendee-service-source/ci/tasks/reroute-green.yml
    params:
      USERNAME: {{cf-user}}
      PASSWORD: {{cf-password}}
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: https://attendee-service-autotomic-vitrifiability.cfapps.io

- name: remove_blue
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [reroute_green]
  - task: remove_blue
    file: attendee-service-source/ci/tasks/remove-blue.yml
    params:
      USERNAME: {{cf-user}}
      PASSWORD: {{cf-password}}
